In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import random

In [4]:
# 1. Definimos la cantidad de filas deseadas (1 millón)
cantidad = 1000000

In [5]:
# 2. Conjunto de datos base reales/coherentes para la simulación de Cancún
influencers_pool = ["@travel_cancun", "@beach_vibe", "@mexico_explorers", "@lifestyle_blogger", "@paradise_seek", "@cancun_sunsets"]
tipos_post_pool = ["foto", "video", "reel", "carrusel"]
fechas_pool = ["2026-05-01", "2026-05-10", "2026-05-15", "2026-05-20", "2026-05-24"]

In [6]:
# 3. Creación del DataFrame de 1,000,000 de registros usando comprensión de listas
df_instagram = pd.DataFrame({
    "influencer": [random.choice(influencers_pool) for _ in range(cantidad)],
    "likes": [random.randint(100, 50000) for _ in range(cantidad)],         # Rango de likes realista
    "comentarios": [random.randint(5, 2500) for _ in range(cantidad)],      # Rango de comentarios realista
    "fecha": [random.choice(fechas_pool) for _ in range(cantidad)],
    "tipo_post": [random.choice(tipos_post_pool) for _ in range(cantidad)]
})

In [7]:
df_instagram.shape

(1000000, 5)

In [8]:
df_instagram.dtypes

influencer     object
likes           int64
comentarios     int64
fecha          object
tipo_post      object
dtype: object

In [9]:
df_instagram.head()

          influencer  likes  comentarios       fecha tipo_post
0  @mexico_explorers  34010         2011  2026-05-24  carrusel
1    @cancun_sunsets  19142         1478  2026-05-20      foto
2     @travel_cancun  31425         1358  2026-05-15      reel
3        @beach_vibe  24552          677  2026-05-10      reel
4  @mexico_explorers  34063          196  2026-05-01      foto

In [10]:
df_instagram.memory_usage(deep=True).sum() / (1024**2)

np.float64(184.13883876800537)

In [11]:
print("Promedio de Likes:", df_instagram["likes"].mean())
print("Promedio de Comentarios:", df_instagram["comentarios"].mean())

Promedio de Likes: 25057.958298
Promedio de Comentarios: 1253.284211

In [12]:
df_instagram.groupby("tipo_post")[["likes", "comentarios"]].mean()

                  likes  comentarios
tipo_post
carrusel   25062.771195  1252.648851
foto       25113.120749  1253.021456
reel       25017.576300  1254.112770
video      25038.512264  1253.352408

In [13]:
df_instagram.groupby("influencer")["likes"].sum().sort_values(ascending=False)

influencer
@cancun_sunsets       4183630289
@lifestyle_blogger    4180248537
@beach_vibe           4177752616
@paradise_seek        4172896694
@travel_cancun        4165704704
@mexico_explorers     4157991250
Name: likes, dtype: int64